language: python
dist: xenial
python:
  - 3.6
install:
  - export VENV=/home/travis/build/env
  - python3 -m venv ${VENV}
  - echo ${TRAVIS_BUILD_DIR}
  - echo ${VENV}
  - cd ${TRAVIS_BUILD_DIR}
  - ${VENV}/bin/pip install -e .

script:
  - ${VENV}/bin/pytest webapp/test
