language: python
dist: xenial
python:
  - 3.6
install:
  - export VENV=~/env
  - python3 -m venv $VENV
  - echo pwd
  - echo ${TRAVIS_BUILD_DIR}
  - cd ${TRAVIS_BUILD_DIR}/CoxBase-Webapp && $VENV/bin/pip install -e .

script:
  - $VENV/bin/pytest webapp/test
