language: python
services:
  - mysql
before_install:
  - mysql -u root < ${TRAVIS_BUILD_DIR}/webapp/scripts/sql/createuser.sql
  - mysql -u root < ${TRAVIS_BUILD_DIR}/webapp/scripts/sql/createdb.sql

dist: xenial
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - python3.6 ${TRAVIS_BUILD_DIR}/webapp/test/test_analysis_page.py 
script:
  - coverage run -m pytest webapp/test
after_success:
  coveralls
