language: python
services:
  - mysql
before_install:
  - mysql -u root < ${TRAVIS_BUILD_DIR}/webapp/script/sql/createuser.sql
  - mysql -u root < ${TRAVIS_BUILD_DIR}/webapp/script/sql/createdb.sql

dist: xenial
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - python3.6 ${TRAVIS_BUILD_DIR}/webapp/test/test_analysis_page.py 
script:
  - pytest webapp/test
