"""included null

Revision ID: 4ee61fdafbd3
Revises: 
Create Date: 2019-08-05 12:20:41.980126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ee61fdafbd3'
down_revision = None
branch_labels = None
depends_on = None

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RepeatSizeISPCR',
    sa.Column('ID', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('ms01', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms03', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms20', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms21', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms22', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms23', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms24', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms26', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms27', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms28', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms30', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms31', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms33', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms34', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ID'], ['ProductLengthISPCR.ID'], name='RepeatSizeISPCR_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('RepeatNumberISPCR',
    sa.Column('ID', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('ms01', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms03', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms20', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms21', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms22', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms23', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms24', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms26', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms27', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms28', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms30', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms31', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms33', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms34', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ID'], ['ProductLengthISPCR.ID'], name='RepeatNumberISPCR_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('ProductLengthISPCR',
    sa.Column('ID', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('ms01', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms03', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms20', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms21', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms22', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms23', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms24', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms26', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms27', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms28', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms30', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms31', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms33', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms34', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('FlankLengthISPCR',
    sa.Column('ID', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('ms01', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms03', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms20', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms21', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms22', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms23', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms24', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms26', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms27', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms28', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms30', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms31', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms33', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ms34', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ID'], ['ProductLengthISPCR.ID'], name='FlankLengthISPCR_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
