def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('home', '/')
    config.add_route('search_results', '/result/{item}')
    config.add_route('No_entry', '/result/noentry/{item}')
    config.add_route('search_page', '/result')
    config.add_route('detailed_view', '/result/details/{uid}')
    config.add_route('wiki_view', '/wiki')
    config.add_route('wikipage_add', '/wiki/add')
    config.add_route('wikipage_view', '/wiki/{uid}')
    config.add_route('wikipage_edit', '/wiki/{uid}/edit')
