name: CoxBase webapp build and test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}  
    - name: Show working dir
      shell: bash
      run: ls
    - name: Shutdown Default Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - name: Install MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
          host port: 3306
          container port: 3306
          mysql version: '8.0'
          mysql user: root
          mysql password: root
          
    - name: Start MySQL
      run: sudo service mysql start
    - name: Verify MySQL
      run: mysql --user=root --password=root
    - name: List existing SQL databases
      run: mysql --user=root --password=root --execute="show databases;" <--- my_db is not shown

    - name: Load database
      run: |
          sudo /etc/init.d/mysql start
          mysql -u root < webapp/scripts/sql/createuser.sql
          mysql -u root < webapp/scripts/sql/createdb.sql
          mysql -u root < webapp/scripts/sql/mlva_schema.sql
          mysql -u root < webapp/scripts/sql/insert_data.sql
    - run: pip install -r requirements.txt
    - run: pip install coverage
    - run: pip install coveralls
    - run: coverage run -m pytest webapp/test
    - run: coveralls

